services:
  caddy:
    image: caddy:latest
    container_name: Caddy
    restart: unless-stopped
    depends_on:
      - maudev_astro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - maudev_network

  maudev_astro:
    image: maudev:latest
    container_name: MauDev
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 4321
      ASTRO_DB_REMOTE_URL: ${ASTRO_DB_REMOTE_URL}
      ASTRO_DB_APP_TOKEN: ${ASTRO_DB_APP_TOKEN}
    ports:
      - "4321:4321"
    networks:
      - maudev_network

volumes:
  caddy_data:
  caddy_config:

networks:
  maudev_network:
